# Generated by Django 4.0.5 on 2023-01-16 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('language', models.CharField(choices=[('EN', 'Anglais'), ('FR', 'Français'), ('SR', 'Serbe')], max_length=30)),
            ],
        ),
    ]
