# Generated by Django 4.0.5 on 2023-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='teaser_picture',
            field=models.ImageField(blank=True, upload_to='teasers/'),
        ),
    ]
