# Generated by Django 4.0.5 on 2023-01-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_teaser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='teaser_picture',
            field=models.ImageField(blank=True, upload_to='teaser_pictures/'),
        ),
    ]
